"""The takes ledger's resolution rules, checked against built fixtures rather than the archive.

Every rule in `ledger.py` reads one of five independent things about a directory
-- whether it has a manifest, where its type comes from, where its held state
comes from, whether anything reads it, and whether its newest take is younger
than what read it -- and combines them. The eighteen-case table below is a
pairwise covering set over those five factors (`coverwise generate`, seed
20260923, five constraints: a manifest-derived source needs a manifest, and a
citing-record-derived source needs something that read the directory), so every
pair of factor values is exercised by at least one row.

**Two of the eighteen combinations expose a real coupling rather than a gap in
the fixture.** A manifest's `prepared` list is one physical list that both the
type rule (does it hold `40 03 00`) and the held rule (is it non-empty at all)
read, so a row asking for `type_source=manifest_prepared` with a *different*
`held_source` still finds held answered from the same list -- correctly, since
the manifest did say what the unit was prepared into. `_expected_held` below
computes that rather than the row's nominal label, and says so at each site.
"""

from __future__ import annotations

import json
import os
from datetime import datetime
from pathlib import Path

import numpy as np
import pytest

from soundings import ledger, takes

UNIT = "unit-x"
STAGE = "efx-time"
TYPE_VALUE = "01 50"
HELD_ADDR = "40 42 22"
HELD_BYTES = "01"
MEASURED_AT = "2026-01-01T00:00:00+00:00"
MEASURED_EPOCH = datetime.fromisoformat(MEASURED_AT).timestamp()


def _wav(dirpath: Path, stem: str, *, mtime: float | None = None) -> Path:
    path = takes.write(dirpath / stem, np.zeros(480, dtype=np.float32), 48000)
    if mtime is not None:
        os.utime(path, (mtime, mtime))
    return path


def _publish(root: Path, name: str, argv: list[str], *, measured_at: str | None) -> str:
    out = root / "data" / "units" / UNIT / STAGE / name
    out.parent.mkdir(parents=True, exist_ok=True)
    envelope = {
        "record": {
            "schema_version": 2,
            "unit_id": UNIT,
            "stage": argv[0],
            "invocation": argv,
            "measured_at": measured_at,
        }
    }
    out.write_text(json.dumps(envelope))
    return out.relative_to(root).as_posix()


def _intermediate(root: Path, path: Path, argv: list[str], *, payload: dict | None = None) -> str:
    path.parent.mkdir(parents=True, exist_ok=True)
    envelope = {"record": {"invocation": argv, "measured_at": None}, **(payload or {})}
    path.write_text(json.dumps(envelope))
    return path.relative_to(root).as_posix()


# --------------------------------------------------------------------------
# The pairwise table: (manifest, type_source, held_source, consumed, mtime).
# Generated by `coverwise generate` (seed 20260923) over
#   manifest: present, absent
#   type_source: manifest_type, manifest_prepared, citing_record, dirname, none
#   held_source: manifest_prepared, citing_invocation, none
#   consumed: none, direct, via_cache_record
#   mtime: older_than_record, newer_than_record
# under the five constraints:
#   IF manifest = absent THEN type_source != manifest_type
#   IF manifest = absent THEN type_source != manifest_prepared
#   IF manifest = absent THEN held_source != manifest_prepared
#   IF consumed = none THEN type_source != citing_record
#   IF consumed = none THEN held_source != citing_invocation
# 18 rows, 100% pairwise coverage.
# --------------------------------------------------------------------------

PAIRWISE_CASES = [
    ("present", "manifest_type", "none", "via_cache_record", "newer_than_record"),
    ("present", "dirname", "citing_invocation", "direct", "older_than_record"),
    ("absent", "dirname", "citing_invocation", "via_cache_record", "newer_than_record"),
    ("absent", "citing_record", "none", "direct", "newer_than_record"),
    ("present", "citing_record", "manifest_prepared", "via_cache_record", "older_than_record"),
    ("present", "manifest_type", "none", "none", "older_than_record"),
    ("absent", "none", "none", "via_cache_record", "older_than_record"),
    ("present", "none", "manifest_prepared", "direct", "newer_than_record"),
    ("present", "manifest_prepared", "manifest_prepared", "none", "older_than_record"),
    ("absent", "none", "none", "none", "newer_than_record"),
    ("present", "manifest_prepared", "none", "direct", "newer_than_record"),
    ("absent", "dirname", "none", "none", "newer_than_record"),
    ("present", "manifest_type", "citing_invocation", "direct", "newer_than_record"),
    ("present", "dirname", "manifest_prepared", "none", "older_than_record"),
    ("present", "manifest_prepared", "citing_invocation", "via_cache_record", "older_than_record"),
    ("absent", "none", "citing_invocation", "direct", "newer_than_record"),
    ("absent", "citing_record", "citing_invocation", "direct", "older_than_record"),
    ("present", "manifest_type", "manifest_prepared", "via_cache_record", "older_than_record"),
]


def _expected_held(type_source: str, held_source: str) -> tuple[dict | None, str | None]:
    """The manifest's `prepared` list is one list, read by two rules.

    Whenever `type_source` is `manifest_prepared`, that list is non-empty for the
    type rule's own reason, and the held rule -- whose source (1) is simply "the
    manifest's prepared list, if it holds anything" -- finds it too, regardless of
    what `held_source` nominally asks for. Rows 9 and 11 above exercise this: row
    11 asks for `held_source=none` but the manifest's list is not empty, so held
    is answered anyway.
    """
    if type_source == "manifest_prepared" or held_source == "manifest_prepared":
        value = {}
        if type_source == "manifest_prepared":
            value["40 03 00"] = TYPE_VALUE
        if held_source == "manifest_prepared":
            value[HELD_ADDR] = HELD_BYTES
        return value, "manifest_prepared"
    if held_source == "citing_invocation" and type_source == "citing_record":
        return {HELD_ADDR: HELD_BYTES}, "citing_invocation"
    return None, None


@pytest.mark.parametrize("manifest_state,type_source,held_source,consumed,mtime", PAIRWISE_CASES)
def test_ledger_pairwise(tmp_path, manifest_state, type_source, held_source, consumed, mtime):
    root = tmp_path
    name = "efx-params-01-50-case" if type_source == "dirname" else "case-dir"
    take_dir = root / ".cache" / "takes" / name
    take_dir.mkdir(parents=True)
    wav_mtime = MEASURED_EPOCH + (3600 if mtime == "newer_than_record" else -3600)
    _wav(take_dir, "struck_kit-064-00", mtime=wav_mtime)

    prepared_entries = []
    manifest: dict = {}
    if type_source == "manifest_type":
        manifest["type"] = TYPE_VALUE
    if type_source == "manifest_prepared":
        prepared_entries.append({"address": "40 03 00", "bytes": TYPE_VALUE})
    if held_source == "manifest_prepared":
        prepared_entries.append({"address": HELD_ADDR, "bytes": HELD_BYTES})
    if prepared_entries:
        manifest["prepared"] = prepared_entries
    if manifest_state == "present":
        (take_dir / "takes-manifest.json").write_text(json.dumps(manifest))

    argv_tail: list[str] = []
    if type_source == "citing_record":
        argv_tail += ["--type", TYPE_VALUE]
    if held_source == "citing_invocation":
        # No --type of its own unless the row's type source is this record: a
        # record that states no type is not taken to match the directory's.
        argv_tail += ["--held", f"{HELD_ADDR}={HELD_BYTES}"]

    record_id = None
    inter_id = None
    if consumed == "direct":
        record_id = _publish(
            root, "case.json", [STAGE, f".cache/takes/{name}", *argv_tail], measured_at=MEASURED_AT
        )
    elif consumed == "via_cache_record":
        inter_id = _intermediate(
            root,
            root / ".cache" / "inter-case" / "routing.json",
            ["contrast", f".cache/takes/{name}"],
        )
        record_id = _publish(
            root, "case.json", [STAGE, ".cache/inter-case", *argv_tail], measured_at=MEASURED_AT
        )

    found = ledger.build(UNIT, root=root, started=MEASURED_EPOCH + 10**7)
    entry = found["directories"][name]

    expected_type = None if type_source == "none" else TYPE_VALUE
    expected_type_from = None if type_source == "none" else type_source
    assert entry["type"] == expected_type
    assert entry["type_from"] == expected_type_from
    assert entry["type_conflict"] is None

    expected_held, expected_held_from = _expected_held(type_source, held_source)
    assert entry["held"] == expected_held
    assert entry["held_from"] == expected_held_from

    if consumed == "none":
        assert entry["consumed_by"] == []
        assert entry["rewritten_after"] == []
        assert entry["unchecked"] == []
    else:
        via = "direct" if consumed == "direct" else [inter_id]
        assert entry["consumed_by"] == [{"record": record_id, "via": via}]
        assert entry["unchecked"] == []
        if mtime == "newer_than_record":
            assert entry["rewritten_after"] == [record_id]
        else:
            assert entry["rewritten_after"] == []


# --------------------------------------------------------------------------
# The six standalone cases the pairwise table does not reach.
# --------------------------------------------------------------------------


def test_type_conflict_between_dirname_and_manifest_prepared(tmp_path):
    root = tmp_path
    take_dir = root / ".cache" / "takes" / "efx-params-01-50-conflict"
    take_dir.mkdir(parents=True)
    _wav(take_dir, "struck_kit-0-00")
    (take_dir / "takes-manifest.json").write_text(
        json.dumps({"prepared": [{"address": "40 03 00", "bytes": "01 51"}]})
    )

    found = ledger.build(UNIT, root=root)
    entry = found["directories"]["efx-params-01-50-conflict"]
    assert entry["type"] is None
    assert entry["type_from"] is None
    assert entry["type_conflict"] == [
        {"source": "manifest_prepared", "value": "01 51"},
        {"source": "dirname", "value": "01 50"},
    ]


def test_settings_from_citing_regex_on_the_file_name(tmp_path):
    root = tmp_path
    take_dir = root / ".cache" / "takes" / "held-run"
    take_dir.mkdir(parents=True)
    _wav(take_dir, "held-16-0120-40-03-04-016-00")
    record_id = _publish(
        root,
        "settings.json",
        [
            STAGE,
            ".cache/takes/held-run",
            "--setting",
            r"held-16-0120-40-03-04-(?P<value>\d{3})",
        ],
        measured_at=MEASURED_AT,
    )

    found = ledger.build(UNIT, root=root)
    entry = found["directories"]["held-run"]
    assert entry["settings"] == {"016": 1}
    assert entry["settings_from"] == f"citing_regex:{record_id}"


def test_settings_absent_with_no_manifest_and_no_citing_record(tmp_path):
    root = tmp_path
    take_dir = root / ".cache" / "takes" / "untouched"
    take_dir.mkdir(parents=True)
    _wav(take_dir, "struck_kit-0-00")

    found = ledger.build(UNIT, root=root)
    entry = found["directories"]["untouched"]
    assert entry["settings"] is None
    assert entry["settings_from"] == "absent"


def test_depth_exceeded_on_a_four_hop_chain(tmp_path):
    root = tmp_path
    take_dir = root / ".cache" / "takes" / "deep"
    take_dir.mkdir(parents=True)
    _wav(take_dir, "struck_kit-0-00")

    _intermediate(root, root / ".cache" / "chain0" / "step.json", ["contrast", ".cache/chain1"])
    _intermediate(root, root / ".cache" / "chain1" / "step.json", ["contrast", ".cache/chain2"])
    _intermediate(root, root / ".cache" / "chain2" / "step.json", ["contrast", ".cache/chain3"])
    (root / ".cache" / "chain3").mkdir(parents=True)

    record_id = _publish(root, "chained.json", [STAGE, ".cache/chain0"], measured_at=MEASURED_AT)

    found = ledger.build(UNIT, root=root)
    unbound = {u["record"]: u["reason"] for u in found["unbound_records"]}
    assert unbound[record_id] == "depth_exceeded"


def test_unchecked_when_measured_at_is_null(tmp_path):
    root = tmp_path
    take_dir = root / ".cache" / "takes" / "no-timestamp"
    take_dir.mkdir(parents=True)
    _wav(take_dir, "struck_kit-0-00")
    record_id = _publish(root, "old.json", [STAGE, ".cache/takes/no-timestamp"], measured_at=None)

    found = ledger.build(UNIT, root=root)
    entry = found["directories"]["no-timestamp"]
    assert entry["unchecked"] == [record_id]
    assert entry["rewritten_after"] == []


def test_held_conflict_when_the_citing_record_names_a_different_type(tmp_path):
    root = tmp_path
    take_dir = root / ".cache" / "takes" / "efx-params-01-50-heldconflict"
    take_dir.mkdir(parents=True)
    _wav(take_dir, "struck_kit-0-00")
    record_id = _publish(
        root,
        "mismatch.json",
        [
            STAGE,
            ".cache/takes/efx-params-01-50-heldconflict",
            "--type",
            "01 51",
            "--held",
            f"{HELD_ADDR}={HELD_BYTES}",
        ],
        measured_at=MEASURED_AT,
    )

    found = ledger.build(UNIT, root=root)
    entry = found["directories"]["efx-params-01-50-heldconflict"]
    # dirname says 01 50; the citing record's own --type says 01 51, which is
    # itself a citing_record type candidate -- so type is a conflict too, and
    # the held offer is excluded for asserting a type ("01 51") that differs
    # from the directory's (null, because of that very conflict).
    assert entry["type"] is None
    assert entry["type_conflict"] == [
        {"source": "citing_record", "value": "01 51"},
        {"source": "dirname", "value": "01 50"},
    ]
    assert entry["held"] is None
    assert entry["held_from"] is None
    assert entry["held_conflict"] == [
        {
            "record": record_id,
            "source": "citing_invocation",
            "record_type": "01 51",
            "dir_type": None,
        }
    ]


def test_held_not_taken_from_a_record_that_states_no_type(tmp_path):
    root = tmp_path
    take_dir = root / ".cache" / "takes" / "untyped-reader"
    take_dir.mkdir(parents=True)
    _wav(take_dir, "struck_kit-0-00")
    (take_dir / "takes-manifest.json").write_text(json.dumps({"type": TYPE_VALUE}))
    record_id = _publish(
        root,
        "untyped.json",
        [STAGE, ".cache/takes/untyped-reader", "--held", f"{HELD_ADDR}={HELD_BYTES}"],
        measured_at=MEASURED_AT,
    )

    found = ledger.build(UNIT, root=root)
    entry = found["directories"]["untyped-reader"]
    assert entry["type"] == TYPE_VALUE
    assert entry["held"] is None
    assert entry["held_from"] is None
    assert entry["held_conflict"] == [
        {
            "record": record_id,
            "source": "citing_invocation",
            "record_type": None,
            "dir_type": TYPE_VALUE,
        }
    ]


# --------------------------------------------------------------------------
# Smoke tests: what success criteria 1 and 2 ask of `build` directly.
# --------------------------------------------------------------------------


def test_every_wav_directory_gets_exactly_one_entry_and_a_well_formed_type(tmp_path):
    root = tmp_path
    plain = root / ".cache" / "takes" / "plain"
    plain.mkdir(parents=True)
    _wav(plain, "struck_kit-0-00")
    typed = root / ".cache" / "takes" / "efx-params-02-0a"
    typed.mkdir(parents=True)
    _wav(typed, "struck_kit-0-00")
    conflicted = root / ".cache" / "takes" / "efx-params-03-00-x"
    conflicted.mkdir(parents=True)
    _wav(conflicted, "struck_kit-0-00")
    (conflicted / "takes-manifest.json").write_text(json.dumps({"type": "03 01"}))

    found = ledger.build(UNIT, root=root)
    assert set(found["directories"]) == {"plain", "efx-params-02-0a", "efx-params-03-00-x"}
    for entry in found["directories"].values():
        if entry["type"] is not None:
            assert entry["type_conflict"] is None
        elif entry["type_conflict"] is not None:
            assert len(entry["type_conflict"]) >= 2
        # else: type is null with no source at all, which is the third
        # allowed state -- nothing here is silently dropped.


def test_unbound_reason_codes_are_all_in_the_closed_vocabulary(tmp_path):
    root = tmp_path
    take_dir = root / ".cache" / "takes" / "anything"
    take_dir.mkdir(parents=True)
    _wav(take_dir, "struck_kit-0-00")
    _publish(root, "missing.json", [STAGE, ".cache/gone"], measured_at=MEASURED_AT)
    _publish(root, "dead-end.json", [STAGE, ".cache/empty-dir"], measured_at=MEASURED_AT)
    (root / ".cache" / "empty-dir").mkdir(parents=True)

    found = ledger.build(UNIT, root=root)
    reasons = {u["reason"] for u in found["unbound_records"]}
    assert reasons <= set(ledger.REASON_CODES)
    assert reasons == {"path_missing", "chain_ends_without_takes"}


def test_query_helpers_over_a_built_ledger(tmp_path):
    root = tmp_path
    read_dir = root / ".cache" / "takes" / "efx-params-01-50-read"
    read_dir.mkdir(parents=True)
    _wav(read_dir, "struck_kit-0-00", mtime=MEASURED_EPOCH - 3600)
    _publish(
        root, "read.json", [STAGE, ".cache/takes/efx-params-01-50-read"], measured_at=MEASURED_AT
    )
    unread_dir = root / ".cache" / "takes" / "never-read"
    unread_dir.mkdir(parents=True)
    _wav(unread_dir, "struck_kit-0-00")

    found = ledger.build(UNIT, root=root)
    assert ledger.load(root) is None
    (root / ledger.LEDGER_PATH).parent.mkdir(parents=True, exist_ok=True)
    (root / ledger.LEDGER_PATH).write_text(json.dumps(found))
    reloaded = ledger.load(root)
    assert reloaded == found

    rows = ledger.row(reloaded, "01 50", "40 03 03")
    assert set(rows) <= {"efx-params-01-50-read"}

    unread_rows = [name for name, _ in ledger.unread(reloaded)]
    assert "never-read" in unread_rows
    assert "efx-params-01-50-read" not in unread_rows

    assert ledger.rewritten(reloaded) == []


def test_take_settings_resolve_each_take_the_way_build_counts_them(tmp_path):
    root = tmp_path
    cited = root / ".cache" / "takes" / "held-run"
    cited.mkdir(parents=True)
    for stem in ("held-16-lowfreq-012-00", "held-16-lowfreq-013-00", "held-16-flat-00-00"):
        _wav(cited, stem)
    _publish(root, "settings.json",
             [STAGE, ".cache/takes/held-run", "--setting", r"held-16-lowfreq-(?P<value>\d{3})"],
             measured_at=MEASURED_AT)
    listed = root / ".cache" / "takes" / "walked"
    listed.mkdir(parents=True)
    for stem in ("tone-000-00", "tone-000-01", "tone-rate-009-00", "tone-out-00"):
        _wav(listed, stem)
    (listed / "takes-manifest.json").write_text(json.dumps({"takes": [
        {"file": "tone-000-00.wav", "setting": "000"},
        {"file": "tone-000-01.wav", "setting": "000"},
        {"file": "tone-rate-009-00.wav", "setting": "rate-009"},
        {"file": "tone-out-00.wav", "setting": "out"},
    ]}))

    found = ledger.build(UNIT, root=root)
    by_take = ledger.take_settings(root, "held-run", found["directories"]["held-run"])
    assert by_take == {"held-16-lowfreq-012-00.wav": "012", "held-16-lowfreq-013-00.wav": "013"}
    walked = ledger.take_settings(root, "walked", found["directories"]["walked"])
    assert walked == {"tone-000-00.wav": "000", "tone-000-01.wav": "000",
                      "tone-rate-009-00.wav": "rate-009", "tone-out-00.wav": "out"}
    for rel, resolved in (("held-run", by_take), ("walked", walked)):
        counts: dict[str, int] = {}
        for setting in resolved.values():
            counts[setting] = counts.get(setting, 0) + 1
        assert counts == found["directories"][rel]["settings"]
